<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * A single-use shareable invite link generated by a user from one of their
     * grants. `expires_at` is the effective expiry (>= now + 72h at generation).
     * Consumed at signup: `used_at` + `invited_user_id` are set and the new
     * account's `referred_by_invite_id` points back here, forming the tree.
     */
    public function up(): void
    {
        Schema::create('invites', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('inviter_user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('invite_grant_id')->nullable()->constrained('invite_grants')->nullOnDelete();
            $table->timestamp('expires_at')->nullable();
            $table->timestamp('used_at')->nullable();
            $table->foreignId('invited_user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('revoked_at')->nullable();
            $table->timestamps();

            $table->index(['inviter_user_id', 'used_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('invites');
    }
};
